variables:
  # Path where packages (nuget or app packages) will be copied to.
  PackageOutputPath: $(Build.ArtifactStagingDirectory)
  
  # For Application.Building.Light optimizations
  IsLightBuild: $[eq(variables['Build.Reason'], 'PullRequest')]

  IsCanaryBranch: $[startsWith(variables['Build.SourceBranch'], 'refs/heads/canaries/')]
  IsReleaseBranch: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))]

  ANDROID_NDK_HOME: C:\Microsoft\AndroidNDK64\android-ndk-r16b
  ANDROID_NDK_PATH: C:\Microsoft\AndroidNDK64\android-ndk-r16b
  AndroidNdkDirectory: C:\Microsoft\AndroidNDK64\android-ndk-r16b

jobs:
- job: Windows # Build UWP/Android/NuGet
  strategy:
    maxParallel: 3
    matrix:
      UWP:
        ApplicationPlatform: UWP_x64
        ArtifactName: UWP
      Android:
        ApplicationPlatform: Android
        ArtifactName: Android
      Packages:
        ApplicationPlatform: Packages
        GeneratePackageOnBuild: true
        ArtifactName: Packages
  pool:
    vmImage: windows-2019
  
  steps:
    - template: build/stage-build.yml

- job: MacOS # Build iOS/macOS
  strategy:
    maxParallel: 2
    matrix:
      iOS:
        ApplicationPlatform: iPhone
        ArtifactName: iOS
      macOS:
        ApplicationPlatform: macOS
        ArtifactName: macOS
  pool:
    vmImage: macOS-10.15
    
  variables:
  - name: SkipUnknownFrameworks
    value: true # Used by TargetFrameworks.Filtering package
  - group: apple.appstore.distribution # Variables for certificate

  steps:
  - task: InstallAppleCertificate@2
    displayName: Install Apple Certificate
    inputs:
      certSecureFile: 'apple.appstore.distribution.p12' # Name of the p12 certificate
      certPwd: '$(appleappstorecertificatepassword)' 
      keychain: 'temp'
      deleteCert: true
  
  - task: InstallAppleProvisioningProfile@1
    displayName: 'Install Apple Provisioning Profile'
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'UnoMaterial.mobileprovision'

  # Apply workaround for https://github.com/xamarin/xamarin-macios/issues/10652
  - bash: |
        curl -o xamarinmac.pkg 'https://bosstoragemirror.blob.core.windows.net/wrench/xcode12.4/a4c70e7d04e3904d17aa60f6d640eb048081c757/4477741/package/notarized/xamarin.mac-7.4.0.10.pkg'
        sudo installer -pkg xamarinmac.pkg -target /
    displayName: Apply Xamarin.mac workaround

  - template: build/stage-build.yml

- job: Linux

  pool:
    vmImage: 'ubuntu-18.04'

  container: unoplatform/wasm-build:2.2

  variables:
    ArtifactName: WASM
    SkipUnknownFrameworks: True

  steps:
    - template: build/stage-build-wasm.yml
