variables:
  # Path where packages (nuget or app packages) will be copied to.
  PackageOutputPath: $(Build.ArtifactStagingDirectory)
  
  # For Application.Building.Light optimizations
  IsLightBuild: $[eq(variables['Build.Reason'], 'PullRequest')]

  # For release conditions
  IsReleaseBranch: $[or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))]

jobs:
- job: Windows # Build UWP/Android/NuGet
  strategy:
    maxParallel: 3
    matrix:
      UWP:
        ApplicationPlatform: UWP_x64
        ArtifactName: UWP
      Android:
        ApplicationPlatform: Android
        ArtifactName: Android
      Packages:
        ApplicationPlatform: Packages
        GeneratePackageOnBuild: true
        ArtifactName: Packages
  pool:
    vmImage: windows-2019
  
  steps:
    - template: build/stage-build.yml

- job: MacOS # Build iOS/macOS
  strategy:
    maxParallel: 2
    matrix:
      iOS:
        ApplicationPlatform: iPhone
        ArtifactName: iOS
      macOS:
        ApplicationPlatform: macOS
        ArtifactName: macOS
  pool:
    vmImage: macOS-10.15
    
  variables:
  - name: SkipUnknownFrameworks
    value: true # Used by TargetFrameworks.Filtering package
  - group: apple.appstore.distribution # Variables for certificate

  steps:
  - task: InstallAppleCertificate@2
    displayName: Install Apple Certificate
    inputs:
      certSecureFile: 'apple.appstore.distribution.p12' # Name of the p12 certificate
      certPwd: '$(appleappstorecertificatepassword)' 
      keychain: 'temp'
      deleteCert: true
  
  - task: InstallAppleProvisioningProfile@1
    displayName: 'Install Apple Provisioning Profile'
    inputs:
      provisioningProfileLocation: 'secureFiles'
      provProfileSecureFile: 'UnoMaterial.mobileprovision'

  - template: build/stage-build.yml

- job: Linux

  pool:
    vmImage: 'ubuntu-18.04'

  container: unoplatform/wasm-build:2.2

  variables:
    ArtifactName: WASM
    SkipUnknownFrameworks: True

  steps:
    - template: build/stage-build-wasm.yml
